-- สร้างตาราง "users"
CREATE TABLE "users" (
    "userId" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    "username" VARCHAR(50) NOT NULL UNIQUE,
    "password" VARCHAR(100) NOT NULL,
    "Lname" VARCHAR(100) NOT NULL,
    "Fname" VARCHAR(100) NOT NULL,
    "Contact_relatives" VARCHAR(10),
    "Contact_number" VARCHAR(10) NOT NULL,
    "ALevelss" VARCHAR(10) NOT NULL DEFAULT 'user',
    "Start_Account" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, -- ไม่ใช้ AT TIME ZONE
    PRIMARY KEY("userId")
);

-- สร้างตาราง "Room"
CREATE TABLE "Room" (
    "roomId" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    "floor" INTEGER NOT NULL,
    "username" VARCHAR(50) NOT NULL,
    "Date_Time" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, -- ไม่ใช้ AT TIME ZONE
    PRIMARY KEY("roomId"),
    FOREIGN KEY("username") REFERENCES "users"("username") ON DELETE CASCADE
);

-- สร้างตาราง "Bill_Payment"
CREATE TABLE "Bill_Payment" (
    "Bill_PaymentId" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    "username" VARCHAR(50) NOT NULL,
    "Name_Bill_payment" VARCHAR(100) NOT NULL,
    "Payment_Amount" DECIMAL NOT NULL,
    "Status_Payment" INTEGER NOT NULL DEFAULT 0,
    "Data_Time" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, -- ไม่ใช้ AT TIME ZONE
    "End_Payment" VARCHAR(255) NOT NULL,
    PRIMARY KEY("Bill_PaymentId"),
    FOREIGN KEY("username") REFERENCES "users"("username") ON DELETE CASCADE
);

-- สร้างตาราง "Repairman"
CREATE TABLE "Repairman" (
    "RepairmanId" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    "position" VARCHAR(50) NOT NULL,
    "username" VARCHAR(50) NOT NULL,
    "Salary" DECIMAL NOT NULL,
    "Status_online" VARCHAR(30) NOT NULL DEFAULT 'ofline',
    PRIMARY KEY("RepairmanId"),
    FOREIGN KEY("username") REFERENCES "users"("username") ON DELETE CASCADE
);

-- สร้างตาราง "Sevice"
CREATE TABLE "Sevice" (
    "SeviceId" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    "username" VARCHAR(50) NOT NULL,
    "RepairmanId" INTEGER NOT NULL,
    "Appointment_day" VARCHAR(20) NOT NULL,
    "Appointment_time" VARCHAR(20) NOT NULL,
    "status" VARCHAR(50) NOT NULL DEFAULT 'Waiting',
    "Date_Time" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, -- ไม่ใช้ AT TIME ZONE
    PRIMARY KEY("SeviceId"),
    FOREIGN KEY("username") REFERENCES "users"("username") ON DELETE CASCADE,
    FOREIGN KEY("RepairmanId") REFERENCES "Repairman"("RepairmanId") ON DELETE CASCADE
);

-- สร้างตาราง "Chatfloor"
CREATE TABLE "Chatfloor" (
    "ChatfloorId" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    "floor" INTEGER NOT NULL,
    "message" VARCHAR(255) NOT NULL,
    "username" VARCHAR(50) NOT NULL,
    "Date_Time" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, -- ไม่ใช้ AT TIME ZONE
    PRIMARY KEY("ChatfloorId"),
    FOREIGN KEY("username") REFERENCES "users"("username") ON DELETE CASCADE
);

-- สร้างตาราง "ChatLegal_person"
CREATE TABLE "ChatLegal_person" (
    "ChatLegal_personId" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    "username_user" VARCHAR(50),
    "username_Legal" VARCHAR(50),
    "message" INTERVAL NOT NULL,
    "Date_Time" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, -- ไม่ใช้ AT TIME ZONE
    PRIMARY KEY("ChatLegal_personId"),
    FOREIGN KEY("username_user") REFERENCES "users"("username") ON DELETE CASCADE,
    FOREIGN KEY("username_Legal") REFERENCES "users"("username") ON DELETE CASCADE
);

-- สร้างตาราง "Post"
CREATE TABLE "Post" (
    "PostId" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    "message" VARCHAR(255) NOT NULL,
    "img" VARCHAR(255) NOT NULL,
    "username" VARCHAR(50) NOT NULL,
    "Approval" VARCHAR(30) NOT NULL,
    "Data_Time" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, -- ไม่ใช้ AT TIME ZONE
    PRIMARY KEY("PostId"),
    FOREIGN KEY("username") REFERENCES "users"("username") ON DELETE CASCADE
);

-- สร้างตาราง "nontify"
CREATE TABLE "nontify" (
    "nontifyId" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    "message" VARCHAR(255) NOT NULL,
    "img" VARCHAR(255),
    "Expiration_date" VARCHAR(20),
    PRIMARY KEY("nontifyId")
);

-- สร้างตาราง "Viewed_notifications"
CREATE TABLE "Viewed_notifications" (
    "Viewed_notificationsId" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    "username" VARCHAR(50),
    "nontifyId" INTEGER,
    PRIMARY KEY("Viewed_notificationsId"),
    FOREIGN KEY("username") REFERENCES "users"("username") ON DELETE CASCADE,
    FOREIGN KEY("nontifyId") REFERENCES "nontify"("nontifyId") ON DELETE CASCADE
);
